### ISSUE TITLE
ERROR While running flb pro.exe

### ISSUE THREAD

**Issue by NotJINXZ** [P-DennyGamingYT/FLB#1]
![2021-12-20 19_09_42-C__Users_unkno_AppData_Local_Temp_scoped_dir79696_1657276047_FLB Pro exe](https://user-images.githubusercontent.com/58348317/146849204-49af7b39-e196-448c-968e-bed48e23e873.png)

**Comment by P-DennyGamingYT** [comment]
oh lol I guess I need to compile differently

**Comment by P-DennyGamingYT** [comment]
FIXED IN v1.0.1a

**Comment by P-DennyGamingYT** [comment]
FIXED IN v1.0.1a
